

[20.03.2018 10:29:40] Exception
Массив не может быть неопределенным.
Имя параметра: bytes
   в System.Text.Encoding.GetString(Byte[] bytes)
   в ULA.Devices.PICON2.Presentation.ViewModels.Picon2ModuleInfoViewModel.<OnReadExecute>d__7.MoveNext() в C:\Users\Гусачок\Desktop\ULA\Devices\PICON2\ULA.Devices.PICON2.Presentation\ViewModels\Picon2ModuleInfoViewModel.cs:строка 72
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)


[20.03.2018 10:31:00] Exception
Массив не может быть неопределенным.
Имя параметра: bytes
   в System.Text.Encoding.GetString(Byte[] bytes)
   в ULA.Devices.PICON2.Presentation.ViewModels.Picon2ModuleInfoViewModel.<OnReadExecute>d__7.MoveNext() в C:\Users\Гусачок\Desktop\ULA\Devices\PICON2\ULA.Devices.PICON2.Presentation\ViewModels\Picon2ModuleInfoViewModel.cs:строка 62
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)


[23.03.2018 10:59:43] Exception
Ссылка на объект не указывает на экземпляр объекта.
   в ULA.Business.DataServices.DeviceLogLoadingService.<ReadNextLogFromDevice>d__6.MoveNext() в C:\ULA 2k17\Business\ULA.Business\DataServices\DeviceLogLoadingService.cs:строка 60
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   в ULA.Presentation.ViewModels.Interactions.LogInteractionViewModel.<OnRefreshExecute>d__11.MoveNext() в C:\ULA 2k17\Presentation\ULA.Presentation\ViewModels\Interactions\LogInteractionViewModel.cs:строка 78
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)


[23.03.2018 14:28:14] Exception
Ссылка на объект не указывает на экземпляр объекта.
   в ULA.Business.DataServices.DeviceLogLoadingService.<ReadNextLogFromDevice>d__6.MoveNext() в C:\ULA 2k17\Business\ULA.Business\DataServices\DeviceLogLoadingService.cs:строка 41
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   в ULA.Presentation.ViewModels.Interactions.LogInteractionViewModel.<OnRefreshExecute>d__11.MoveNext() в C:\ULA 2k17\Presentation\ULA.Presentation\ViewModels\Interactions\LogInteractionViewModel.cs:строка 78
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)


[26.03.2018 14:04:11] Exception
Ссылка на объект не указывает на экземпляр объекта.
   в ULA.Business.DataServices.DeviceLogLoadingService.<ReadNextLogFromDevice>d__6.MoveNext() в C:\ULA 2k17\Business\ULA.Business\DataServices\DeviceLogLoadingService.cs:строка 41
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   в ULA.Presentation.ViewModels.Interactions.LogInteractionViewModel.<OnRefreshExecute>d__11.MoveNext() в C:\ULA 2k17\Presentation\ULA.Presentation\ViewModels\Interactions\LogInteractionViewModel.cs:строка 78
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)


[26.03.2018 15:20:39] Exception
Ссылка на объект не указывает на экземпляр объекта.
   в ULA.Business.DataServices.DeviceLogLoadingService.<ReadNextLogFromDevice>d__6.MoveNext() в C:\ULA 2k17\Business\ULA.Business\DataServices\DeviceLogLoadingService.cs:строка 41
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   в ULA.Presentation.ViewModels.Interactions.LogInteractionViewModel.<OnRefreshExecute>d__11.MoveNext() в C:\ULA 2k17\Presentation\ULA.Presentation\ViewModels\Interactions\LogInteractionViewModel.cs:строка 78
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)


[26.03.2018 15:45:42] Exception
Ссылка на объект не указывает на экземпляр объекта.
   в ULA.Business.DataServices.DeviceLogLoadingService.<ReadNextLogFromDevice>d__6.MoveNext() в C:\ULA 2k17\Business\ULA.Business\DataServices\DeviceLogLoadingService.cs:строка 41
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   в ULA.Presentation.ViewModels.Interactions.LogInteractionViewModel.<OnRefreshExecute>d__11.MoveNext() в C:\ULA 2k17\Presentation\ULA.Presentation\ViewModels\Interactions\LogInteractionViewModel.cs:строка 78
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)


[26.03.2018 15:47:41] Exception
Ссылка на объект не указывает на экземпляр объекта.
   в ULA.Business.DataServices.DeviceLogLoadingService.<ReadNextLogFromDevice>d__6.MoveNext() в C:\ULA 2k17\Business\ULA.Business\DataServices\DeviceLogLoadingService.cs:строка 41
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   в System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   в ULA.Presentation.ViewModels.Interactions.LogInteractionViewModel.<OnRefreshExecute>d__11.MoveNext() в C:\ULA 2k17\Presentation\ULA.Presentation\ViewModels\Interactions\LogInteractionViewModel.cs:строка 78
--- Конец трассировка стека из предыдущего расположения, где возникло исключение ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)


[22.05.2018 12:09:43] Exception
Метод или операция не реализована.
   в ULA.Presentation.ViewModels.Interactions.CommandOnTemplateInteractionViewModel.OnEditTemplateCommand() в C:\ULA 2k17\Presentation\ULA.Presentation\ViewModels\Interactions\CommandOnTemplateInteractionViewModel.cs:строка 70
   в MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   в System.Windows.Controls.Primitives.ButtonBase.OnClick()
   в System.Windows.Controls.Button.OnClick()
   в System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   в System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   в System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   в System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   в System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   в System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   в System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   в System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   в System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   в System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   в System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   в System.Windows.Input.InputManager.ProcessStagingArea()
   в System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   в System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   в System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   в System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)


[22.05.2018 12:09:46] Exception
Метод или операция не реализована.
   в ULA.Presentation.ViewModels.Interactions.CommandOnTemplateInteractionViewModel.OnEditTemplateCommand() в C:\ULA 2k17\Presentation\ULA.Presentation\ViewModels\Interactions\CommandOnTemplateInteractionViewModel.cs:строка 70
   в MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   в System.Windows.Controls.Primitives.ButtonBase.OnClick()
   в System.Windows.Controls.Button.OnClick()
   в System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   в System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   в System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   в System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   в System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   в System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   в System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   в System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   в System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   в System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   в System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   в System.Windows.Input.InputManager.ProcessStagingArea()
   в System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   в System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   в System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   в System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   в MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   в System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   в System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
